In [5]:
#EXERCICE 6
a=int(input("type a :"))
b=int(input("type b :"))
c=int(input("type c :"))
x = np.array([a, b, c])
y = np.array([c, b, a])
import numpy as np
def Matrix (x,y) :
    print("Original array1:")
    print(x)
    print("Original array1:")
    print(y)
    print("\nCovariance matrix of the said arrays:",np.cov(x, y))
    return (x,y)
Matrix(x,y)

type a :0
type b :1
type c :2
Original array1:
[0 1 2]
Original array1:
[2 1 0]

Covariance matrix of the said arrays: [[ 1. -1.]
 [-1.  1.]]


(array([0, 1, 2]), array([2, 1, 0]))